from crewai import Task

def get_research_task(agent, company_name: str):
    return Task(
        description=f"""
        Research the company: {company_name}. Search specifically for "{company_name} company startup profile funding".
        Gather:
        1. What the company does (product/service)
        2. Founded year, HQ, team size
        3. Funding history — total raised, investors, last round
        4. Key competitors (at least 3)
        5. Recent news (last 6 months)
        6. Tech stack or product features
        7. Revenue or growth metrics (if public)
        Use the search tool multiple times with different queries.
        Output all raw findings as a structured list.
        """,
        agent=agent,
        expected_output=(
            "A detailed bullet-point list of all research findings, "
            "organized by the 7 categories above."
        )
    )

def get_analysis_task(agent, company_name: str):
    return Task(
        description=f"""
        Using the research data about {company_name}, produce:
        1. One-line company summary
        2. Business model — how they make money
        3. Key strengths (2-3 bullet points)
        4. Key risks or weaknesses (2-3 bullet points)
        5. Market opportunity
        6. Competitive position
        7. Verdict: Promising / Neutral / Risky
        """,
        agent=agent,
        expected_output="A structured analysis covering all 7 sections."
    )

def get_writing_task(agent, company_name: str):
    return Task(
        description=f"""
        Write a final intelligence report for {company_name}.
        FORMAT:
        # {company_name} — Intelligence Report

        ## Overview
        ## Quick Facts
        ## What They Do
        ## Business Model
        ## Strengths
        ## Risks
        ## Competitive Landscape
        ## Recent News
        ## Verdict
        ---
        *Report generated by StartupScope*
        """,
        agent=agent,
        expected_output="A complete formatted markdown intelligence report."
    )
